---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: managed-cluster
  region: us-east-2

vpc: #vpc-02679738c68185c22
  subnets:
      us-east-2c: { id: subnet-0283e489d6390d59c }
      us-east-2b: { id: subnet-0bcf1e6c59083c18b }
      us-east-2a: { id: subnet-0edc2ca51f7f776e4 }
      
managedNodeGroups:
  - name: ng-1
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    availabilityZones: ["us-east-2a", "us-east-2b"]
    instancesDistribution:
      maxPrice: 0.2
      instanceTypes: ["t2.small", "t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
    ssh:
      allow: true
      publicKeyName: eks-cluster
    tags:
      nodegroup-role: nginx
    iam:
      withAddonPolicies:
        autoScaler: true

  - name: ng-2
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    availabilityZones: ["us-east-2b", "us-east-bc"]
    instancesDistribution:
      maxPrice: 0.2
      instanceTypes: ["t2.small", "t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
    ssh:
      allow: true
      publicKeyName: eks-cluster
    tags:
      nodegroup-role: traefik
    iam:
      withAddonPolicies:
        autoScaler: true
