---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: managed-cluster
  region: us-east-2
      
nodeGroups:
  - name: ng-1
    minSize: 1
    maxSize: 3
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
      allow: true
      publicKeyName: eks-cluster-key
    labels:
      nodegroup-type: nginx
    iam:
      withAddonPolicies:
        autoScaler: true

  - name: ng-2
    minSize: 1
    maxSize: 3
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
      allow: true
      publicKeyName: eks-cluster-key
    labels:
      nodegroup-type: alpine
    iam:
      withAddonPolicies:
        autoScaler: true
        
